[win_srv]
win-tgt-jcc ansible_host=192.168.20.163

[linux_srv]
lin-tgt-jcc ansible_host=192.168.20.170

[all_srv:children]
win_srv
linux_srv

#Windows exclusive variables
[win_srv:vars]
ansible_connection=winrm
ansible_winrm_transport=basic
ansible_port=5985
ansible_winrm_scheme=http

#Linux exclusive variables
[linux_srv:vars]
ansible_connection=ssh
ansible_user=ec2-user

