[win_srv]
i-0189627f9c6235fc9

[linux_srv]
i-0eedd127b6a6ab912 

[all_srv:children]
win_srv
linux_srv

# Shared variables
[all_srv:vars]
ansible_connection=aws_ssm
ansible_aws_ssm_region=us-east-2
ansible_aws_ssm_bucket_name=murphyslab-jcc-ssm-ansible-data-f768d6dd

#Windows exclusive variables
[win_srv:vars]
ansible_shell_type=powershell
ansible_user=Administrator

#Linux exclusive variables
[linux_srv:vars]
ansible_user=ssm-user
ansible_remote_tmp=/tmp/.ansible/tmp

