---
- name: Configure Linux SSH Key
  hosts: linux_srv
  gather_facts: true

  tasks:
    - name: Add Terraform-generated public key to authorized_keys
      ansible.posix.authorized_key:
        user: ec2-user
        state: present
        key: "{{ new_public_key }}"
      become: yes